### ISSUE TITLE
Not compatible with omeka v3.2.1

### ISSUE THREAD

**Issue by frixion9** [biblibre/omeka-s-module-Solr#18]
After upgrading to newer version of omeka (v3.2.1) few problems occured:

- items were not shown on portal unless I "refreshed" them using "edit all items" option on omeka page
- items disappear from portal site if I choose "clear index" option while reindexing and I have to repeat the step above (using your[ search module](https://github.com/biblibre/omeka-s-module-Search))
- If I change any field on node pages (indexing or search field) I have to first clear index, then refresh items and afrer that reindex everything again to apply changes and show items on portal site.

**Comment by jajm** [comment]
When you choose to "clear index", the index is emptied first. So it is normal to not have results at first. Did you wait for the background job to finish ? Do you see anything suspicious in the job log ?

If you change indexing fields, you have to rebuild the index to apply changes, that's normal.

Search fields shouldn't change anything for the indexing process, I don't see why changing only search fields require a full index rebuild. Can you provide detailed steps to reproduce this bug ?

You don't have to "edit all items". The rebuild index job does the same, but much faster since items are not updated.

What versions of modules Search and Solr are you using ?

**Comment by frixion9** [comment]
Hi, 

sorry for late reply, I wanted to test everything thoroughly. It seems that problem wasn't with module, but with one item I had on portal. After deleting it, everything works as it should.

**Comment by jajm** [comment]
Do you know what caused the problem exactly in this item ?
A faulty item should not be able to break the search index rebuild, so it might be a bug in the search or solr module

**Comment by frixion9** [comment]
Hi, 

sorry again for late reply.  

It seems that the language tag was missing and that caused the problem. It may be that the problem occurred due to our restrictions regarding the language tags on items. I will do some more testing in the following days and let you know about the results.
